
# NB! Set your site's url, otherwise stuff will break :)

url: "https://hatat5.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)
baseurl: ''

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Nishant Subramani"
title: "Nishant Subramani"
description: "Website of Nishant Subramani" 
keywords: "nishant, subramani, personal, northwestern, nyu, new york university, cilvr, mll, scale, scale ai"
favicon: "/img/favicon.ico"

############
# Timeline #
############

events:
  - image: "/img/timeline/scale.png"
    date: "April 2020 - Present"
    description: "ML Research Scientist at Scale AI" 
  - image: "/img/timeline/aif.jpeg"
    date: "July 2019 - January 2020"
    description: "Research Scientist at AI Foundation" 
  - image: "/img/timeline/nyu.jpg"
    date: "September 2017 - May 2019"
    description: "MS in Computer Science (Machine Learning) at New York University" 
  - image: "/img/timeline/salesforce.png"
    date: "March 2017 - August 2017"
    description: "Deep Learning Research Intern at Salesforce Research" 
  - image: "/img/timeline/neuralnet.png"
    date: "March 2016 - March 2017"
    description: "Research Assistant in Deep Learning & NLP at Northwestern University" 
  - image: "/img/timeline/northwestern.png"
    date: "January 2016 - March 2017"
    description: "MS in Computer Science at Northwestern University"    
  - image: "/img/timeline/ethzurich.png"
    date: "September 2015 - January 2016"
    description: "Master's Exchange Student in Computer Science at ETH Zurich"
  - image: "/img/timeline/stanford.png"
    date: "June 2015 - January 2016"
    description: "Research Assistant in Biomedical Informatics at Stanford University"      
  - image: "/img/timeline/neuralnet.png"
    date: "July 2014 - March 2015"
    description: "Research Assistant in Neural Network Language Modeling at Northwestern University"
  - image: "/img/timeline/northwestern.png"
    date: "September 2013 - March 2017"
    description: "BA in Statistics at Northwestern University"
    
# First image of the Timeline

timeline-img: "/img/timeline/default.png"

################
# Header layout #
################

#black-favicon: "/img/black-lab-glass.ico"

#background-img: "/img/galaxy.jpg"
background-img: "/img/hobbit_hole.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: False 
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 20
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Nishant Subramani: Machine Learning Researcher"

me-img: "/img/author2.png"

##############################
# Color the browser elements #
##############################
color-browser: "#0000ff"
apple-status-bar-style: 'black'

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 9 

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True

syntax-highlight: True

###########
# Contact #
###########

email: "nishant.subramani23@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Nishant Subramani is a Machine Learning Researcher at Scale AI who is experienced in machine learning, deep learning, natural language processing, and fake speech detection and synthesis."
author_blurb_image: "/img/author2.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/nishantsubramani23/"
  - title: "twitter"
    url: "https://twitter.com/nsubramani23/"
  - title: "github"
    url: "https://github.com/hatat5/"
  - title: "linkedin"
    url: "https://linkedin.com/in/nishantsubramani/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/default.png"

##################
# GPG on Keybase #
##################

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Timeline: 'timeline'
  About: 'about'
  Research: 'research'
  Blog: 'latest-post'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate

